FROM wordpress:php8.2-apache


RUN a2enmod rewrite

RUN printf "%s\n" \
    "# BEGIN WordPress" \
    "<IfModule mod_rewrite.c>" \
    "RewriteEngine On" \
    "RewriteBase /" \
    "RewriteRule ^index\.php$ - [L]" \
    "RewriteCond %{REQUEST_FILENAME} !-f" \
    "RewriteCond %{REQUEST_FILENAME} !-d" \
    "RewriteRule . /index.php [L]" \
    "</IfModule>" \
    "# END WordPress" \
    > /var/www/html/.htaccess

RUN chown -R www-data:www-data /var/www/html
